### ISSUE TITLE
"npm install" clarification

### ISSUE THREAD

**Issue by stela5** [dmnsgn/gulp-frontend-boilerplate#12]
Sorry if this is a newbie/obvious question, but your https://github.com/dmnsgn/gulp-frontend-boilerplate#init instructions say `Then each time you clone the repo, use: $ npm install`

If this just needs to happen when you clone the repo, why don't you just include it in your https://github.com/dmnsgn/gulp-frontend-boilerplate#clone-this-repository section?  For example: `git clone --depth 1 https://github.com/dmnsgn/gulp-frontend-boilerplate.git && cd gulp-frontend-boilerplate && rm -rf .git && npm install`

Perhaps at a higher level, I'd like to understand the developer workflow a little better using your promising tool.  Thanks in advance!

**Comment by stela5** [comment]
At the moment, the way I read it is:

1. run the provided command to clone *dmnsgn/gulp-frontend-boilerplate* and remove the .git version control folder
2. run `npm run init` to configure the app
3. add your new app to your own version control (i.e. *acme/myapp*) -- the node_modules folder is excluded via .gitignore
4. developer Bob from the Acme Company clones the myapp repo to his local laptop and runs `npm install` to get the necessary npm modules and begins development.

Am I on the right track?

**Comment by dmnsgn** [comment]
> If this just needs to happen when you clone the repo, why don't you just include it in your https://github.com/dmnsgn/gulp-frontend-boilerplate#clone-this-repository section?

You are supposed to clone the repo dmnsgn/gulp-frontend-boilerplate once and then run the init step once to set up your project (`npm run init`). This init step is modifying your `package.json` dependencies to fit your needs; that is why the `npm install` is called after and can't be include in the "get me the boilerplate files on my machine" step.

You got the workflow right in your second comment ;) Is it clearer for you ?

**Comment by stela5** [comment]
Thanks for the clarification
