### ISSUE TITLE
vendor.min.js doesnt compile

### ISSUE THREAD

**Issue by craft37** [dmnsgn/gulp-frontend-boilerplate#15]
subj

**Comment by dmnsgn** [comment]
You probably need to install uglify-js globally: `npm install uglify-js -g`. The readme does not specify it. I will try to solve that by adding it as a local dev dependency soon.

**Comment by craft37** [comment]
Thank you.

**Comment by dmnsgn** [comment]
Should be fixed in the 1.4.0 version: https://github.com/dmnsgn/gulp-frontend-boilerplate/commit/9a31d3c64cefaf1696693ba6451ad06a40711ed7#diff-4646546d57c5cd24dfdec09bc5183484R77
Running `gulp --env prod` on a fresh install compile vendor.min.js.
