### ISSUE TITLE
gulp-notify: [Error] unable to minify JavaScript

### ISSUE THREAD

**Issue by Amazing-Space-Invader** [dmnsgn/gulp-frontend-boilerplate#16]
Hello, i have subj bug. How to resolve it?

**Comment by dmnsgn** [comment]
I need more details.
Which command are you running?
What kind of code is inside your `scripts` folder? ES6?

**Comment by Amazing-Space-Invader** [comment]
`npm run prod` and `gulp --env prod`
Yes, ES6 arrow-functions, require and const\let features only.
I found funny thing: if `npm run dev` process runs in background - scripts are compiled, but an error in the console has not disappeared
