### ISSUE TITLE
Compiling JS separately?

### ISSUE THREAD

**Issue by iamryanyu** [dmnsgn/gulp-frontend-boilerplate#19]
I couldn't find a way to separately compile and move JS to /dist/scripts/.

For example, I wanted to add `<script src="scripts/modernizr.min.js"></script>` in `<head>` but I can only add additional JS in vendor.js which will be placed right before </body>.

**Comment by dmnsgn** [comment]
You can add `modernizr.min.js` to `dist/static` and require it from your `index.html`:

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <script src="static/modernizr.min.js"></script>
</head>
<body></body>
</html>
```

**Comment by iamryanyu** [comment]
Ah I see, didn't think of that.

Thanks a lot!
