### ISSUE TITLE
Install requirements should add napa package

### ISSUE THREAD

**Issue by doggy8088** [dmnsgn/gulp-frontend-boilerplate#2]
I'm always get this error:

> npm ERR! gulp-frontend-boilerplate@0.4.7 install: `napa`
> npm ERR! Exit status 1

Then I realize I have to install "napa" package in order to avoid this problem.

> npm install -g napa

**Comment by dmnsgn** [comment]
napa is included as a devDependencies and the install script runs AFTER the package is installed so no need to make it a global dependency.
But it seems that others have had this issue and solved it with `npm install -g napa`: https://github.com/karimsa/gulp-jslint/issues/1#issuecomment-40867597

Looks like an issue with napa itself.

**Comment by doggy8088** [comment]
ack.
